---
meta:
  environment: docker-registry-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: registry
    instances: 1
    networks:
      - name: (( grab networks.default.name ))
        static_ips: (( static_ips(0) ))

disk_pools:
- name: registry
  disk_size: 1024

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random
