---
update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: registry
    templates:
      - { release: docker-registry, name: registry }
    instances: 1
    resource_pool: small_z1
